### ISSUE TITLE
Use of Laravel OPCache ^4.0

### ISSUE THREAD

**Issue by newtongamajr** [appstract/nova-opcache#4]
Hi @ovanschie, any prevision for OPCache 4.0 compatibility?

Thanks in advance!

**Comment by ovanschie** [comment]
I can't think of any breaking changes. I changed it in composer.json, can you help test it?

Should be good to go if you require 'dev-master' in composer.json as the version.

If everything is ok, I can tag a new release.

**Comment by newtongamajr** [comment]
I did that in advance @ovanschie. I forked your repository and did the same change. Everything is working fine!

**Comment by ovanschie** [comment]
Thanks! new release tagged
